using NUnit.Framework;

namespace PocketGems.Parameters.Util
{
    public class ParameterPrefsTest
    {
        private bool _autoGenerateDataOnAssetChange;
        private bool _autoValidateDataOnAssetChange;
        private bool _ShouldGenerateAllData;
        private bool _autoGenerateCodeOnCompilation;
        private bool _enableInspectorAutoSave;
        private bool _playModeHotLoading;
        private bool _doNotDeleteSchemaFile;
        private bool _expandableDrawer;
        private bool _verboseLogs;

        [OneTimeSetUp]
        public void OneTimeSetUp()
        {
            _autoGenerateDataOnAssetChange = ParameterPrefs.AutoGenerateDataOnAssetChange;
            _autoValidateDataOnAssetChange = ParameterPrefs.AutoValidateDataOnAssetChange;
            _ShouldGenerateAllData = ParameterPrefs.ShouldGenerateAllData;
            _autoGenerateCodeOnCompilation = ParameterPrefs.AutoGenerateCodeOnCompilation;
            _enableInspectorAutoSave = ParameterPrefs.EnableInspectorAutoSave;
            _playModeHotLoading = ParameterPrefs.PlayModeHotLoading;
            _doNotDeleteSchemaFile = ParameterPrefs.DoNotDeleteSchemaFile;
            _expandableDrawer = ParameterPrefs.ExpandableDrawer;
            _verboseLogs = ParameterPrefs.VerboseLogs;
        }

        [OneTimeTearDown]
        public void OneTimeTearDown()
        {
            ParameterPrefs.AutoGenerateDataOnAssetChange = _autoGenerateDataOnAssetChange;
            ParameterPrefs.AutoValidateDataOnAssetChange = _autoValidateDataOnAssetChange;
            ParameterPrefs.ShouldGenerateAllData = _ShouldGenerateAllData;
            ParameterPrefs.AutoGenerateCodeOnCompilation = _autoGenerateCodeOnCompilation;
            ParameterPrefs.EnableInspectorAutoSave = _enableInspectorAutoSave;
            ParameterPrefs.PlayModeHotLoading = _playModeHotLoading;
            ParameterPrefs.DoNotDeleteSchemaFile = _doNotDeleteSchemaFile;
            ParameterPrefs.ExpandableDrawer = _expandableDrawer;
            ParameterPrefs.VerboseLogs = _verboseLogs;
        }

        [Test]
        public void SetValues()
        {
            ParameterPrefs.AutoGenerateDataOnAssetChange = false;
            ParameterPrefs.AutoValidateDataOnAssetChange = false;
            ParameterPrefs.ShouldGenerateAllData = false;
            ParameterPrefs.AutoGenerateCodeOnCompilation = false;
            ParameterPrefs.EnableInspectorAutoSave = false;
            ParameterPrefs.PlayModeHotLoading = false;
            ParameterPrefs.DoNotDeleteSchemaFile = false;
            ParameterPrefs.ExpandableDrawer = false;
            ParameterPrefs.VerboseLogs = false;

            Assert.IsFalse(ParameterPrefs.AutoGenerateDataOnAssetChange);
            Assert.IsFalse(ParameterPrefs.AutoValidateDataOnAssetChange);
            Assert.IsFalse(ParameterPrefs.ShouldGenerateAllData);
            Assert.IsFalse(ParameterPrefs.AutoGenerateCodeOnCompilation);
            Assert.IsFalse(ParameterPrefs.EnableInspectorAutoSave);
            Assert.IsFalse(ParameterPrefs.PlayModeHotLoading);
            Assert.IsFalse(ParameterPrefs.DoNotDeleteSchemaFile);
            Assert.IsFalse(ParameterPrefs.ExpandableDrawer);
            Assert.IsFalse(ParameterPrefs.VerboseLogs);

            ParameterPrefs.AutoGenerateDataOnAssetChange = true;
            Assert.IsTrue(ParameterPrefs.AutoGenerateDataOnAssetChange);
            Assert.IsFalse(ParameterPrefs.AutoValidateDataOnAssetChange);
            Assert.IsFalse(ParameterPrefs.ShouldGenerateAllData);
            Assert.IsFalse(ParameterPrefs.AutoGenerateCodeOnCompilation);
            Assert.IsFalse(ParameterPrefs.EnableInspectorAutoSave);
            Assert.IsFalse(ParameterPrefs.PlayModeHotLoading);
            Assert.IsFalse(ParameterPrefs.DoNotDeleteSchemaFile);
            Assert.IsFalse(ParameterPrefs.ExpandableDrawer);
            Assert.IsFalse(ParameterPrefs.VerboseLogs);

            ParameterPrefs.AutoValidateDataOnAssetChange = true;
            Assert.IsTrue(ParameterPrefs.AutoGenerateDataOnAssetChange);
            Assert.IsTrue(ParameterPrefs.AutoValidateDataOnAssetChange);
            Assert.IsFalse(ParameterPrefs.ShouldGenerateAllData);
            Assert.IsFalse(ParameterPrefs.AutoGenerateCodeOnCompilation);
            Assert.IsFalse(ParameterPrefs.EnableInspectorAutoSave);
            Assert.IsFalse(ParameterPrefs.PlayModeHotLoading);
            Assert.IsFalse(ParameterPrefs.DoNotDeleteSchemaFile);
            Assert.IsFalse(ParameterPrefs.ExpandableDrawer);
            Assert.IsFalse(ParameterPrefs.VerboseLogs);

            ParameterPrefs.ShouldGenerateAllData = true;
            Assert.IsTrue(ParameterPrefs.AutoGenerateDataOnAssetChange);
            Assert.IsTrue(ParameterPrefs.AutoValidateDataOnAssetChange);
            Assert.IsTrue(ParameterPrefs.ShouldGenerateAllData);
            Assert.IsFalse(ParameterPrefs.AutoGenerateCodeOnCompilation);
            Assert.IsFalse(ParameterPrefs.EnableInspectorAutoSave);
            Assert.IsFalse(ParameterPrefs.PlayModeHotLoading);
            Assert.IsFalse(ParameterPrefs.DoNotDeleteSchemaFile);
            Assert.IsFalse(ParameterPrefs.ExpandableDrawer);
            Assert.IsFalse(ParameterPrefs.VerboseLogs);

            ParameterPrefs.AutoGenerateCodeOnCompilation = true;
            Assert.IsTrue(ParameterPrefs.AutoGenerateDataOnAssetChange);
            Assert.IsTrue(ParameterPrefs.ShouldGenerateAllData);
            Assert.IsTrue(ParameterPrefs.AutoGenerateCodeOnCompilation);
            Assert.IsFalse(ParameterPrefs.EnableInspectorAutoSave);
            Assert.IsFalse(ParameterPrefs.PlayModeHotLoading);
            Assert.IsFalse(ParameterPrefs.DoNotDeleteSchemaFile);
            Assert.IsFalse(ParameterPrefs.ExpandableDrawer);
            Assert.IsFalse(ParameterPrefs.VerboseLogs);

            ParameterPrefs.EnableInspectorAutoSave = true;
            Assert.IsTrue(ParameterPrefs.AutoGenerateDataOnAssetChange);
            Assert.IsTrue(ParameterPrefs.AutoValidateDataOnAssetChange);
            Assert.IsTrue(ParameterPrefs.ShouldGenerateAllData);
            Assert.IsTrue(ParameterPrefs.AutoGenerateCodeOnCompilation);
            Assert.IsTrue(ParameterPrefs.EnableInspectorAutoSave);
            Assert.IsFalse(ParameterPrefs.PlayModeHotLoading);
            Assert.IsFalse(ParameterPrefs.DoNotDeleteSchemaFile);
            Assert.IsFalse(ParameterPrefs.ExpandableDrawer);
            Assert.IsFalse(ParameterPrefs.VerboseLogs);

            ParameterPrefs.PlayModeHotLoading = true;
            Assert.IsTrue(ParameterPrefs.AutoGenerateDataOnAssetChange);
            Assert.IsTrue(ParameterPrefs.AutoValidateDataOnAssetChange);
            Assert.IsTrue(ParameterPrefs.ShouldGenerateAllData);
            Assert.IsTrue(ParameterPrefs.AutoGenerateCodeOnCompilation);
            Assert.IsTrue(ParameterPrefs.EnableInspectorAutoSave);
            Assert.IsTrue(ParameterPrefs.PlayModeHotLoading);
            Assert.IsFalse(ParameterPrefs.DoNotDeleteSchemaFile);
            Assert.IsFalse(ParameterPrefs.ExpandableDrawer);
            Assert.IsFalse(ParameterPrefs.VerboseLogs);

            ParameterPrefs.DoNotDeleteSchemaFile = true;
            Assert.IsTrue(ParameterPrefs.AutoGenerateDataOnAssetChange);
            Assert.IsTrue(ParameterPrefs.AutoValidateDataOnAssetChange);
            Assert.IsTrue(ParameterPrefs.ShouldGenerateAllData);
            Assert.IsTrue(ParameterPrefs.AutoGenerateCodeOnCompilation);
            Assert.IsTrue(ParameterPrefs.EnableInspectorAutoSave);
            Assert.IsTrue(ParameterPrefs.PlayModeHotLoading);
            Assert.IsTrue(ParameterPrefs.DoNotDeleteSchemaFile);
            Assert.IsFalse(ParameterPrefs.ExpandableDrawer);
            Assert.IsFalse(ParameterPrefs.VerboseLogs);

            ParameterPrefs.ExpandableDrawer = true;
            Assert.IsTrue(ParameterPrefs.AutoGenerateDataOnAssetChange);
            Assert.IsTrue(ParameterPrefs.AutoValidateDataOnAssetChange);
            Assert.IsTrue(ParameterPrefs.ShouldGenerateAllData);
            Assert.IsTrue(ParameterPrefs.AutoGenerateCodeOnCompilation);
            Assert.IsTrue(ParameterPrefs.EnableInspectorAutoSave);
            Assert.IsTrue(ParameterPrefs.PlayModeHotLoading);
            Assert.IsTrue(ParameterPrefs.DoNotDeleteSchemaFile);
            Assert.IsTrue(ParameterPrefs.ExpandableDrawer);
            Assert.IsFalse(ParameterPrefs.VerboseLogs);

            ParameterPrefs.VerboseLogs = true;
            Assert.IsTrue(ParameterPrefs.AutoGenerateDataOnAssetChange);
            Assert.IsTrue(ParameterPrefs.AutoValidateDataOnAssetChange);
            Assert.IsTrue(ParameterPrefs.ShouldGenerateAllData);
            Assert.IsTrue(ParameterPrefs.AutoGenerateCodeOnCompilation);
            Assert.IsTrue(ParameterPrefs.EnableInspectorAutoSave);
            Assert.IsTrue(ParameterPrefs.PlayModeHotLoading);
            Assert.IsTrue(ParameterPrefs.DoNotDeleteSchemaFile);
            Assert.IsTrue(ParameterPrefs.ExpandableDrawer);
            Assert.IsTrue(ParameterPrefs.VerboseLogs);
        }
    }
}
